### ISSUE TITLE
Scheduled task - error

### ISSUE THREAD

**Issue by lazna** [gerardog/gsudo#105]
When try to create new scheduled task with "Run with highest privileges" option, gsudo (expectedly) failed. Only generic exitcode 1 is produced so it is hard to determine specific error in script. Is it possible in such case prompt for user/password (as in case GUI task creation happens) or produce specific exitcode I could display appropriate error message in my scripts?

```
gsudo --debug schtasks /create /TN network_testing /XML task_testing.xml
Debug: IsWindowsApp("C:\WINDOWS\system32\cmd.exe") = False ("C:\WINDOWS\system32\cmd.exe")
Debug: Command to run: C:\WINDOWS\system32\cmd.exe /c schtasks /create /TN network_testing /XML task_testing.xml
Debug: Using Console mode TokenSwitch
Debug: Caller PID: 15016
Debug: Caller SID: S-1-5-21-2888163432-2796349975-2356466950-1001
Debug: Found Named Pipe "ProtectedPrefix\Administrators\gsudo_C0F985BFEDAD672E72CA87F8AE6A268B3251CF2B874676111B75D82FF54250D6".
Debug: Connected via Named Pipe ProtectedPrefix\Administrators\gsudo_C0F985BFEDAD672E72CA87F8AE6A268B3251CF2B874676111B75D82FF54250D6.
Debug: CreateProcessAsUser: C:\WINDOWS\system32\cmd.exe /c schtasks /create /TN network_testing /XML task_testing.xml
Debug: ElevationRequest length 840
Debug: Process token successfully substituted.
ERROR: The user name or password is incorrect.
Info: Process exited with code 1
```

**Comment by gerardog** [comment]
Hi. In your case gsudo succeeded to elevate. But schtasks failed to create the task and returned errorlevel 1 + ‘ERROR: The user name or password is incorrect’ . Your schtasks params are wrong. Open an elevated cmd to take gsudo out of the ecuation and then test your schtask params.

If gsudo fails, the errorlevel would be exactly 999.

**Comment by lazna** [comment]
My schtask params are OK (when XML is imported by GUI it does work fine) but if doing some changes in GUI, it prompt me for entering username and password (not only for elevation click confirmation), could this be a problem?

**Comment by lazna** [comment]
Just found where the problem reside. When I changed `logonType` from `Password` to `InteractiveToken` in the XML file, than schtasks.exe work fine with gsudo

https://docs.microsoft.com/en-us/windows/win32/taskschd/task-scheduler-schema

**Comment by gerardog** [comment]
Do not assume schtasks GUI vs Command Line experience is the same.  

gsudo can elevate commands, will not help you with schtasks quirks. 

**Have you tested what I suggested?** Open a CMD elevated the usual way, **without gsudo involved**. Then test exactly the same command 'schtasks /create /TN network_testing /XML task_testing.xml' without gsudo. Be sure that the intended xml file exists in the current directory and its content is correct too. Spoiler alert: it will fail too, because this is not gsudo's problem. It is how schtasks works. Probably you Xml / command line has a missing or incorrect "user name or password" as Schtasks message indicated.

A little bit of googling: https://rakhesh.com/windows/schtasks-specifying-username-to-run-an-imported-task-under/

```
C:\Users\gerar>schtasks /create /TN network_testing /XML test.xml
ERROR: Access is denied.

C:\Users\gerar>gsudo schtasks /create /TN network_testing /XML test.xml
SUCCESS: The scheduled task "network_testing" has successfully been created.
```
