### ISSUE TITLE
Issue: Unable to automatically execute script on gsudo start

### ISSUE THREAD

**Issue by DanAtkinson** [gerardog/gsudo#112]
## Issue Description

Is there a way of forcing gsudo to execute a script on start similar to the `/k` switch? I can't find anything in `gsudo config` that would allow me to always execute a script, such as `refreshenv` whenever gsudo is started.

## Steps to Reproduce

1. Install `gsudo` and `openssl` using chocolatey.
2. Run `gsudo`.
3. Run `openssl`.

## What I see 
The error `'openssl' is not recognized as an internal or external command,
operable program or batch file.`

## What I expect to see
The openssl command prompt.

## Anything else
The only way to resolve this is by running `refreshenv`. This is a [chocolatey script](https://github.com/chocolatey/choco/blob/master/src/chocolatey.resources/redirects/RefreshEnv.cmd) which can run to read in environment variables. I run Windows using a LAPS profile (Local Administrator Password Solution) so it may be this, but I feel that this would be useful functionality in any case.

**Important:** Normally, in non-gsudo terminal windows, I get around this by adding `/k refreshenv` to my terminal settings. However, I can't see anything similar in gsudo. I also have the same issues in VS Code when doing npm work as this is installed via `nvm` - also from chocolatey.

## Screenshots
Below, I have detailed how I can only access `openssl` in gsudo once I run `refreshenv`. openssl is not recognised until this is run. openssl is never available to non-admin users (this is fine).

![image](https://user-images.githubusercontent.com/23440/137556257-e09707f3-3aa0-4245-85ec-b37e4cc3642c.png)

## Context:
 - Windows version: **21HL (OS Build 19043.1237)**
 - gsudo version:     **1.0.2**

**Comment by gerardog** [comment]
Let me see if I understand the issue:

* LAPS basically means that you are not using UAC in the common "Admin Approval Mode". IE: You log in as non-local-admin user. Then on gsudo UAC popup, you type in a local admin user and password (instead of clicking in a `Yes` button. Right?
* If that is the case, then the problem is that the process to elevate run as local-admin, but inherits the non-admin environment variables: Which means it's Path variable does not contains OpenSSL, which is the root of the problem.

There are many ways to address this situation: 

* Add OpenSSL path to the non-admin Path env var. This way, the REFRESHENV is no longer needed (at least for openssl). 
* Falling back to gsudo's `attached mode`. In this mode, the elevated process will run as admin, and with admin's environment variables. (No need to run REFRESHENV then). You can do this with `gsudo --attached` / `gsudo --attached command`. If this works for you, you can force this for any further gsudo elevation with `gsudo config ForceAttachedConsole true`.... Side effect: redirecting gsudo's output will fail ( `gsudo dir > myfile.txt` will create an empty myfile.txt and show `dir` output on screen )

* Or, if you want to run something immediately after elevation, send the `/k` argument to `cmd.exe`, for example:

```
C:\>gsudo cmd /k refreshenv
Refreshing environment variables from registry for cmd.exe. Please wait...Finished..

C:\#
```

Do any of these options solve your problem?
Regards

**Comment by DanAtkinson** [comment]
Thank you for the suggestion re `AutoRun` value in `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Command Processor`. I was not aware of this and it's exactly the functionality I was looking for.

Thanks again
Dan
