### ISSUE TITLE
Issue: not reporting the right username in environment variable(s)

### ISSUE THREAD

**Issue by JanDeDobbeleer** [gerardog/gsudo#113]
## Steps to Reproduce

1.  Run gsudo from a user without elevated right
2. Authenticate as another user
3. The environment which is copied over is still pointing to the current user (`USERNAME `)

What I would expect is that those settings also point to the elevated user (as that's who you are).
We've been having a chat on this, and my assumption would be that this is the responsibility of gsudo to ensure env vars are correct as not only oh-my-posh could rely on this which makes it so any user could potentially do unwanted actions. 

## Screenshots
You can check the original issue reported [here](https://github.com/JanDeDobbeleer/oh-my-posh/issues/1024).

## Context:
 - Windows version: any
 - gsudo version: any

**Comment by devinmcelheran** [comment]
I second this issue. I recently started using gsudo and when I launch an elevated tab in Windows Terminal it carries the environment variables of my non-elevated user account (a different account altogether) into the elevated shell. This results in the elevated shell attempting to load my non-elevated user's PowerShell profile. This could have been useful for a unified profile if it weren't for the fact that it fails to load because it's using the literal path in the variable when my non-elevated account's Documents folder is redirected to OneDrive.

I think that a command flag/switch indicating whether to user the parent processes' environment variables or the associated elevated user's would be ideal.

**Comment by gerardog** [comment]
Hi. You all are right. This is a problem when running as a different user. A somewhat similar ticket was filled in #112.
There are several "elevation modes", different mechanisms to elevate in the current console that gsudo uses, and the current default is TokenSwitch, which uses the invoker environment to launch the process and the elevated gsudo replaces its security token with an elevated one. This generates the problem you are reporting. 

Before that, the Attached mode was the default. That one does not produces this problem, because the elevated app is started by the elevated gsudo, then attached to non-elevated console. But a few other issues (which favored TokenSwitch) will resurface and now would need to be addressed in a different way. 

Right now you can use `gsudo --attached` or `gsudo config ForceAttachedConsole true` to avoid this problem.

For a next release,
- See viability to detect whether "Running As a different user" was used. The real problem here is that the elevation mode is determined long before running the elevated gsudo (UAC consent). If so, fall back automatically to attached mode.
- If that can't be done, and I am thinking out loud here, maybe find a more elegant set of config keys. `gsudo config ElevationMode Attached` instead of having ForceXX and ForceYY.
- Fix remaining attached mode issues.

**Comment by devinmcelheran** [comment]
The ```--attached``` flag works perfectly in Windows Terminal, thank you. I think this might be a good flag to mention in the readme. Thank you so much.

**Comment by gerardog** [comment]
You may want to upgrade to v1.1.0, because it solves the Ctrl-C issue with attached mode.

**Comment by gerardog** [comment]
A proper fix has been released (in v1.1.1) including several small fixes that also allows the usage of `Invoke-gsudo` cmdlet for this scenario.
