### ISSUE TITLE
Issue: gsudo slmgr.vbs /ipk XXXXX-YYYYY-ZZZMY-PRODU-CTKEY fails with error 0xC004E016

### ISSUE THREAD

**Issue by sebma** [gerardog/gsudo#114]
## Issue Description

The command `gsudo slmgr.vbs /ipk XXXXX-YYYYY-ZZZMY-PRODU-CTKEY` fails with error `0xC004E016` whereas the change of the PK with the graphical method succeeds.
BTW : The command **[gsudo changepk.exe /productkey XXXXX-YYYYY-ZZZMY-PRODU-CTKEY](https://ss64.com/nt/changepk.html)** also succeeds.

## Steps to Reproduce

1. `powershell.exe`
2. `gsudo slmgr.vbs /ipk XXXXX-YYYYY-ZZZMY-PRODU-CTKEY`
3. I got this error message in an OK popup : 
`Error: 0xC004E016 On a computer running Microsoft Windows non-core edition, run 'slui.exe 0x2a 0xC004E016' to display the error text.`

## Screenshots

![image](https://user-images.githubusercontent.com/4569306/140366636-d32849d3-45f0-4207-8069-ec98f50b5323.png)
And the `slui.exe 0x2a 0xC004E016` command pops up this second screenshot : 
![image](https://user-images.githubusercontent.com/4569306/140367001-5708b195-32a9-48d8-9108-abbdd217a782.png)

```ps1
PS Prompt D:> gsudo --debug slmgr.vbs /ipk XXXXX-YYYYY-ZZZMY-PRODU-CTKEY
Debug: Command to run: "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -Command "slmgr.vbs /ipk XXXXX-YYYYY-ZZZMY-PRODU-CTKEY"
Debug: Using Console mode TokenSwitch
Debug: CreateProcessAsUser: "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -Command "slmgr.vbs /ipk XXXXX-YYYYY-ZZZMY-PRODU-CTKEY"
Debug: Elevating process: C:\ProgramData\chocolatey\lib\gsudo\bin\gsudo.exe --debug gsudoelevate --pid 7744
Debug: Elevated instance started.
Debug: Process exited with code 0
```

## Context:
 - Windows version: `Windows 10 Pro 21H1 OS Build 19043, 1288`
 - gsudo version: `gsudo v1.0.2 (Branch.master.Sha.cab27ed3ca23496129320dfed56624274c9a27a6)`

**Comment by gerardog** [comment]
Hi.
To me, it looks like gsudo is working properly. You can confirm by trying the same command but not using gsudo. Open a CMD as administrator, and then running your command `slmgr.vbs /ipk XXXXX-YYYYY-ZZZMY-PRODU-CTKEY` there. You will notice they also fail. 
This means that the problem is not related to how you elevate the command. It is the command itself that is invalid.

If you have problems with `slmgr` or `slui` you should contact Microsoft. My guess is that your product key is invalid or does not match the OS version that you have installed:

![image](https://user-images.githubusercontent.com/3901474/140414536-c263c824-f840-4efe-8eb8-dec104bacd62.png)

Regards

**Comment by sebma** [comment]
@gerardog You're absolutly, man I should have in a CMD as administrator : same error message.
Therefore this has nothing to do with `gsudo` but everything to do with `slmgr.vbs`.
Sorry for the inconvenience.
Closing this issue.
