### ISSUE TITLE
Issue: Running a PowerShell script with brackets in its filename?

### ISSUE THREAD

**Issue by fgimian** [gerardog/gsudo#122]
## Steps to Reproduce

When running a script with brackets in its filename, gsudo seems to be unhappy 😄 

```
C:\Users\Fots\builder [master ≡ +2 ~1 -0 !]> gsudo .\boo.ps1
hello
C:\Users\Fots\builder [master ≡ +3 ~1 -0 !]> gsudo '.\boo hoo.ps1'
hello
C:\Users\Fots\builder [master ≡ +2 ~1 -0 !]> gsudo '.\Configure Windows 11 (Administrator).ps1'
Administrator: The term 'Administrator' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

## Screenshots

Output provided above.

## Context:

 - Windows version: Windows 11 21H2
 - gsudo version: v1.0.2 (Branch.master.Sha.cab27ed3ca23496129320dfed56624274c9a27a6)

**Comment by fgimian** [comment]
I can confirm that the following approach works:

```pwsh
gsudo pwsh '.\Configure Windows 11 (Administrator).ps1'
```

But can you perhaps explain why this is necessary when brackets are present, but not otherwise?

Thanks so much!
Fotis

**Comment by gerardog** [comment]
For how gsudo works refer to the [readme](/gerardog/gsudo#usage-from-powershell--powershell-core):

It says: `For simple commands, without parentheses () or the pipeline operator |, just prepend gsudo.`. 

Then: `For more complex commands, you can pass a string literal with the command to elevate: PS C:\> gsudo 'powershell string command'` (1)

In your case, the actual working full command is **`&  '.\Configure Windows 11 (Administrator).ps1'`**. That is the way to invoke a ps1 file with spaces. If you omit the & it will just print the filename. Now per (1) this command must be put in a string, so it can be elevated by prepending gsudo: `gsudo "& '.\Configure Windows 11 (Administrator).ps1'"` and that works fine. Use that form please.

But why? you ask. PS interprets parenthesis or whatever valid operator not enclosed in quotes **before** calling gsudo: 

E.g. : `gsudo echo (1+1)` actually calls `gsudo echo 3`. The sum is not elevated, something the user may not be expecting.

Imagine you do `gsudo Get-Item .\a.txt | Remove-Item` the only part elevated is `Get-Item .\a.txt` because the pipe splits the command into two, and gsudo is only on the left command. And I bet the user actually wanted to elevate the Remove-Item part.

So:  ** quotes are needed to prevent PS from preprocessing the command-to-be-elevated before elevation.**

Hope that explains it.

**Comment by fgimian** [comment]
> For how gsudo works refer to the [readme](/gerardog/gsudo#usage-from-powershell--powershell-core):
> 
> It says: `For simple commands, without parentheses () or the pipeline operator |, just prepend gsudo.`.
> 
> Then: `For more complex commands, you can pass a string literal with the command to elevate: PS C:\> gsudo 'powershell string command'` (1)
> 
> In your case, the actual working full command is **`& '.\Configure Windows 11 (Administrator).ps1'`**. That is the way to invoke a ps1 file with spaces. If you omit the & it will just print the filename. Now per (1) this command must be put in a string, so it can be elevated by prepending gsudo: `gsudo "& '.\Configure Windows 11 (Administrator).ps1'"` and that works fine. Use that form please.
> 
> But why? you ask. PS interprets parenthesis or whatever valid operator not enclosed in quotes **before** calling gsudo:
> 
> E.g. : `gsudo echo (1+1)` actually calls `gsudo echo 3`. The sum is not elevated, something the user may not be expecting.
> 
> Imagine you do `gsudo Get-Item .\a.txt | Remove-Item` the only part elevated is `Get-Item .\a.txt` because the pipe splits the command into two, and gsudo is only on the left command. And I bet the user actually wanted to elevate the Remove-Item part.
> 
> So: **quotes are needed to prevent PS from preprocessing the command-to-be-elevated before elevation.**
> 
> Hope that explains it.

Thank you so so much for the explanation! 😄
