### ISSUE TITLE
Feature: Chocolatey Bin Shim

### ISSUE THREAD

**Issue by mattcargile** [gerardog/gsudo#123]
Would it be possible to not ignore the `sudo.exe` symlink file to have it be "[shimgen](https://docs.chocolatey.org/en-us/features/shim)-ed" into the `"$env:ChocolateyInstall\bin"` directory? Or is that too many layers of abstraction? It would be nice to remove that extra path from from my `$env:PATH`. I looked around the issues and commits and couldn't find where this was discussed.

**Comment by gerardog** [comment]
This was discussed in #47 and probably a few other places.

The initial gsudo packages did exactly that: create shims for gsudo. No Path variable change. 
I would loved that it worked, but the experience was not as good.

I at that time the shim broke the Ctrl-C behaviour. That may be fixed by now, but haven't checked.
There was another issue with how DOSKEY disliked shims. This means that CMD history (up and down arrows) broke more frequently when there was a shim involved.

Why are you asking this? Is this only about not bloating the PATH variable?

**Comment by mattcargile** [comment]
Thanks for the explanation and my apologies for not searching well enough ( a bit embarrassed :-) ). 

No big problem with the current approach. I was just being picky about the `PATH` bloat. Going to close. It appears the Ctrl+C behavior is still not ideal.

P.S. Big fan. I _love_ the software as is. Works great!
