### ISSUE TITLE
Issue: gsudoModule.psd1 RootModule

### ISSUE THREAD

**Issue by mattcargile** [gerardog/gsudo#127]
## Issue Description
I see you have a `psd1` manifest. It appears all we need is to add `gsudoModule.psm1` to `RootModule` and it will import properly like the below code snippet. Then when we do a `Get-Module` we can see the versioning.

`RootModule = 'gsudoModule.psm1'`

## Steps to Reproduce

1.  `Import-Module -Name "C:\tools\gsudo\Current\gsudoModule.psd1"`

## Screenshots

https://github.com/gerardog/gsudo/blob/0575f14b40ff0fb3d5b799e7b4f5fc3f21df4d54/src/gsudo.extras/gsudoModule.psd1#L12
## Context:
 - Windows version: `v1909`
 - gsudo version:  `1.1.0`

**Comment by gerardog** [comment]
I assume it was ok to leave empty, because:
<img width="447" alt="image" src="https://user-images.githubusercontent.com/3901474/155986090-909e9c29-5fed-4096-a896-50be5af7c4e4.png">

<s>Does it makes any difference adding that line?</s>

**Oh!!,** I see a difference between importing the `.psd1` which gets the correct version number but the incorrect ExportedCommands, versus  importing the `.psm1` which does the opposite. And fixing the `RootModule` fixes that. Thanks! 
I may change all documentation to refer to the `Import-Module .....psd1` file instead of the `.psm1`.

Also, I should have used a better version number instead of `0.0.1`. Will use the build number in the following releases.

**Comment by mattcargile** [comment]
Nice! Yeah I like that.

**Comment by gerardog** [comment]
Given that I know that you have installed v1.1 via choco, please try `gsudo choco upgrade gsudo --version=1.1.1-alpha2 -pre` for testing this specific fix. 😊

**Comment by gerardog** [comment]
BTW: Thank you very, very much @mattcargile for becoming the first gsudo donor!!! You rock!

**Comment by gerardog** [comment]
The problem is that your current directory was `C:\tools\gsudo\current` when you ran `choco upgrade`... from PowerShell... Dully noted... will fix it later on.

**Comment by mattcargile** [comment]
Oh snap! Of course! Thanks.

**Comment by gerardog** [comment]
Fix released in v1.1.1

**Comment by mattcargile** [comment]
Good deal! I had to uninstall and then reinstall. I guess because my alpha build had the same `1.1.1` version as the newest one?
