### ISSUE TITLE
Set-NetIPInterface not working

### ISSUE THREAD

**Issue by lwalker-kforce** [gerardog/gsudo#135]
In a PS script file I use to configure WSL2 with our corporate VPN, I execute the following:
`Set-NetIPInterface -Forwarding Enabled -Verbose -InterfaceAlias 'vEthernet (WSL)'`
If I open and run it from an elevated shell it runs fine. I cannot get to execute correctly with `gsudo`. Running `gsudo -n -w Set-NetIPInterface -Forwarding Enabled -Verbose -InterfaceAlias "vEthernet (WSL)"` yields: 

![image](https://user-images.githubusercontent.com/4869444/162649496-183cb3c8-c6ac-4b37-9fea-4bfcc88b855a.png)

Strangely, using `gsudo` it somehow tries to execute the command in WSL. 

Any help would be appreciated.

**Comment by gerardog** [comment]
Hi, I need more info to figure out what is happening. 

How did you installed and run pwsh? How did you run gsudo exactly. 
> Really helps if you use the "gsudo --debug" flag: For example instead of "gsudo notepad" do "gsudo --debug notepad" 

Please paste the results using --debug, for example: `Set-NetIPInterface -Forwarding Enabled -Verbose -InterfaceAlias 'vEthernet (WSL)'`

Thanks

**Comment by gerardog** [comment]
I was able to reproduce the problem.
Pwsh, when installed as a dotnet global tool, is wrapped in a `` shim process. The shim does a terrible job handling quotes.

<img width="946" alt="image" src="https://user-images.githubusercontent.com/3901474/162681945-840ca4ec-05a6-4014-856d-3f320a3f670e.png">

Your single quotes became double quotes, hence, the '(WSL)' part becomes a pwsh command to invoke pwsh.
Please uninstall pwsh global tool, and install pwsh with other mechanism. 

Otherwise please wait until Microsoft team fixes this issue on their end:
See PowerShell/PowerShell/11747

**Comment by gerardog** [comment]
I see the problem and I do not need more info from your side now.
Still happens when using regular pwsh, so it is a little broader problem.

Nonetheless there is a possibility to fix this on gsudo side, by escaping single quotes with a backtick `` `' ``.
But, this can break other workflows. Will have to test it for a while.

**Comment by gerardog** [comment]
It's not just the global tool that it's broken (PowerShell/PowerShell#11747). PowerShell and Pwsh are broken too (PowerShell/PowerShell#1995) (at least up to latest 7.2.x). 

The global tool doesn't even respect string literals:
<img width="724" alt="image" src="https://user-images.githubusercontent.com/3901474/163078520-d386a8be-2e72-44c5-8a80-d4b6d4c42c06.png">

I sincerely recommend just uninstall the global tool: `dotnet tool uninstall powershell --global`
And install using winget `winget install Microsoft.PowerShell` or Chocolatey `choco install powershell-core`


PowerShell (for one) replaces single quotes with doubles:
<img width="288" alt="image" src="https://user-images.githubusercontent.com/3901474/163085363-e029ef8c-7764-4a99-953e-b7125a6c8f83.png">

This behaviour [is likely to be fixed in pwsh 7.3](https://stackoverflow.com/a/59036879/97471). Which also means any fix I do today won't work in the future.

Pwsh also provides the `--%` "stop parsing symbol" which stops this problem from hapenning too:
`gsudo --% Set-NetIPInterface -Forwarding Enabled -Verbose -InterfaceAlias "vEthernet (WSL)"`

And, finally, gsudo provides invoke-gsudo, which accepts a scriptblock as a parameter.
`invoke-gsudo {Set-NetIPInterface -Forwarding Enabled -Verbose -InterfaceAlias "vEthernet (WSL)"}`

So, please, use one of the alternatives.
