### ISSUE TITLE
`gsudo chocolatey upgrade gsudo` ends up breaking gsudo command

### ISSUE THREAD

**Issue by lostmsu** [gerardog/gsudo#17]
Looks like the install script kills `gsudo`, that runs it. 😂
Workaround is to remove `C:\ProgramData\chocolatey\bin\gsudo.exe` (which is a link) and to reinstall gsudo from a regular elevated console.

**Comment by gerardog** [comment]
Using `gsudo` to upgrade `gsudo` is not supported right now. Please open and use a CMD as administrator. ¯\_(ツ)_/¯

Under some circumstances, surprisingly, it works. 😁

But in your case, you went into what's described in #18, not strictly caused by using gsudo in the command, but a bug because I didnt test the `choco upgrade` scenario correctly. Still, you used the expected workaround! 🎉

Nonetheless, I will leave this issue open until, at least, the scripts properly detects and stops the upgrade if `gsudo` is open, which I am not completely sure if it's possible (chocolatey/choco#1731).
Or, at least, it shows a big warning message.
