### ISSUE TITLE
Issue: `gsudo -s` Doesn't Elevate To `SYSTEM` Using Non-Admin Account

### ISSUE THREAD

**Issue by mattcargile** [gerardog/gsudo#173]
## Issue Description

UPDATE: I think all the below is moot point based on this code? I guess I was misunderstanding what is possible and the current process has to already be admin to elevate to `SYSTEM`? So my best bet is open _2_ below in my _Workarounds_ section?

https://github.com/gerardog/gsudo/blob/c71dac54b64bfaea73d6b5b5d469f9288af43803/src/gsudo/Helpers/ServiceHelper.cs#L99

It appears I am not `SYSTEM` when I use the `-s` parameter from a _Medium_ integrity session of a non-administrator. Tools like `psexec -s` will output `NT AUTHORITY\SYSTEM` from `whoami` when I do something like `sudo psexec -s whoami`. ~Not sure if your method of duplicating the `SYSTEM` token is different from `psexec`? Or maybe `whoami` output is just wrong?~ 

This became an issue with some third-party script I was using to work with the Windows App directory where `TrustedInstaller` was involved. The script wouldn't work because it couldn't accurately tell if the user was `SYSTEM`.

~[Here ](https://gist.github.com/jborean93/33c55bdd47541866dfaea43ab38d2c79)is some `powershell` to run as `SYSTEM` using the `lsass.exe` process. Not sure if you can reliably count on this process existing and might have to loop over all the processes to find one running under `SYSTEM`?~ This is no longer relevant. Apologies for not understanding the issue more.
## Steps to Reproduce

1. Open a `powershell.exe` or `pwsh.exe` with _Medium_ Integrity with a *Non*-Admin account.
2. Issue `gsudo -s whoami` and elevate with a different account which is Administrator
3. Output is the user who ever you elevated the process with instead of `NT AUTHORITY\SYSTEM`.

## Screenshots 

N/A
## Context:
  - Windows version: Win10 21H1 - English

  - gsudo version: v1.4.1 (Branch.tags-v1.4.1.Sha.6dfc9caa8a84aea44341d92fb813615a26f0282b)

### Workarounds
1. Issue `sudo` and pass the _UAC_ prompt. Then issue `sudo -s` . Then `whoami` outputs `NT AUTHORITY\SYSTEM`.
2. Issue `sudo sudo -s`

**Comment by gerardog** [comment]
Hi. This is a though one, that will hopefully help improve the codebase, but wont be fast.
There is a triple user hop NonAdmin -> LocalAdmin (elevated) -> System, and gsudo v1.5 gets it wrong.

In TokenSwitch mode, it is a single hop: NonElevated -> Elevated, but Elevated can pick any token it wants and apply it. (Except for TI, which is super dupa protected). So if you go to System, is still one hop, and works.

But if you are NonAdmin, for security reasons, see [here](https://gerardog.github.io/gsudo/docs/how-it-works#should-the-elevated-process-inherit-the-same-environment-variables) or #113, then Attached Mode is used. Attached Mode requires a triple hop because the process must start as the desired process.

If you build gsudo in debug mode, you can see the unhashed named pipes names (using gsudo status for example).
This is relevant because the pipe name contains the allowed user SID. Which should be NonAdmin, but it is LocalAdmin instead. so it fails.

Workaround:
Call `gsudo gsudo -s`. That will take the double jump to your command, but out of gsudo flawed logic.

**Comment by gerardog** [comment]
The sid mismatch wasnt so hard to fix (d4c861228fd642d3b4d1eaba8dd000c0dbcdfe01)
Signed prerelease, scroll down for artifacts -> installer, or binaries: https://github.com/gerardog/gsudo/actions/runs/3012133390

Windows Defender may be flagging it...

**Comment by mattcargile** [comment]
> The sid mismatch wasnt so hard to fix ([d4c8612](https://github.com/gerardog/gsudo/commit/d4c861228fd642d3b4d1eaba8dd000c0dbcdfe01)) Signed prerelease, scroll down for artifacts -> installer, or binaries: https://github.com/gerardog/gsudo/actions/runs/3012133390

Awesome, this works as I was expecting! 👍🏻 

Side note, I didn't really need to login as `TrustedInstaller` because `SYSTEM` was enough. And FYI, I was talking about [this](https://github.com/AgentRev/WindowsAppsUnfukker) repo.

> Windows Defender may be flagging it...

I use Sentinel One and was able to extract and run the new binary well with no problems. Windows Defender is disabled because of this product.

**Comment by gerardog** [comment]
Solved in v1.5.1
