### ISSUE TITLE
Problem with Chocolatey Install in v0.6.0.2

### ISSUE THREAD

**Issue by antonioyon** [gerardog/gsudo#18]
After upgrading to v0.6.0.2, gsudo stopped working with this error message:

> Cannot find file at '..\\lib\gsudo\tools\gsudo.exe' (C:\ProgramData\chocolatey\lib\gsudo\tools\gsudo.exe). This usually indicates a missing or moved file.

The `gsudo.exe` executable is in the chocolatey\lib\gsudo\bin folder but not chocolatey\lib\gsudo\tools folder. I copied the executable to tools folder as a workaround and it appears to be functional now.

**Comment by gerardog** [comment]
The first choco package that I uploaded for gsudo (`0.3`) used regular choco shims to put gsudo in the `PATH` environment variable. The shims created several problems, so on the next upload `0.4.1` and up to `0.5.2`, the installer script created two symlinks instead, where the shims used to be (`%ChocolateyInstall%\Bin`).
Later, when I uploaded 0.5.3, Chocolatey moderators requested me to first stop writing directly to `%ChocolateyInstall%\Bin`. So I had fewer options: shims caused issues and symlinks on `bin` folder were not allowed... So I switched to adding `gsudo` folder to the `PATH` variable directly. I didn't wanted to pollute the PATH folder, but I had no other option.

Now, the problem that you reported is caused by not properly deleting the old shim/symlink from `%ChocolateyInstall%\Bin` from installations <=0.5.2

The proper workaround is to open a CMD as admin and then delete the old symlink.
```
del "%ChocolateyInstall%\Bin\gsudo.exe"
del "%ChocolateyInstall%\Bin\sudo.exe"
```

But, I've just released 0.6.0.3 choco package (with same binaries as 0.6.0.2~0.6) that should fix this scenario (delete those symlinks). So, as soon as it gets approved, you can do:
`choco upgrade gsudo`
and it should fix it.

Thanks for reporting.
