### ISSUE TITLE
Oh My Posh prompt for gsudo

### ISSUE THREAD

**Issue by 237dmitry** [gerardog/gsudo#184]
## Description

`gsudo status` could be parsed, for example:

```powershell
[bool][int] (gsudo status | Select-String '(?<=Total.+:\s)\d').Matches.Value
```
But it is more convenient to view an environment variable. Something like `$env:GSUDO_CACHE = $true | $false`

**Comment by gerardog** [comment]
- An environment variable won't work for this scenario. Because only the current process (e.g. your current active shell) can cleanly write it's value... A cache session is an independent process, that can't write on other process env. vars., and even if it could, the cache could end anytime (for example by another process running 'gsudo -k'). So if it dies, any environment variable will be outdated.
- I don't understand what are you trying to do. What would you use that env var for? like, oh_my_posh customization ?
- Checking `Total active cache sessions:` will tell you if there is any active cache, but won't tell if the current process can elevate without popup, for that I would use:
    - `[bool]((gsudo status) -like "*Available for this process: True*")`
- Would an official gsudo PowerShell function work? like: Test-IsGsudoCacheAvailable or Test-IsAnyGsudoCacheActive? (naming is draft)

**Comment by 237dmitry** [comment]
Ok, clearly

>  like, oh_my_posh customization ?

Yes, like oh_my_posh, custom prompts.

![gsudo](https://user-images.githubusercontent.com/78153320/193453601-63c750ed-ce65-4474-9600-88320c15821a.png)

**Comment by gerardog** [comment]
In that case, performance is a priority, and `gsudo status` parsing may not be fast enough

This one will tell you if any cache session is active, but the cache may be for another process, (like looking at Total Number).
`[bool]([System.IO.Directory]::GetFiles("\\.\\pipe\\") -like '*gsudo*')`.

**Comment by 237dmitry** [comment]
> In that case, performance is a priority, and gsudo status parsing may not be fast enough

As I use gsudo only in pwsh session I do environment variable for this session, write toggle function for turning on and off cache. Something like:
```powershell
function Set-Cache
{
     if (-not (Test-Path env:gsudo_state))
     { 
         Set-Content env:gsudo_state $true 
         gsudo cache on *>$null
        Write-Warning "gsudo cache on"
    }
    else
    {
         del env:gsudo_state
         gsudo cache off *>$null
         Write-Warning "gsudo cache off"
    }
}
```
This is enough for my needs. Not tested.

**Comment by gerardog** [comment]
Right now my console shows a `#` when elevated. And a `>` when not. The `>` turns white if there is a cache session available.

![image](https://user-images.githubusercontent.com/3901474/198496545-7627178b-ae2e-45c4-b363-08632470f9e7.png)

To do this, the environment variable must be set before each prompt is rendered. So I added this to the $Profile: 

```
function Set-MyPoshContext
{
	if ([bool]((& 'gsudo.exe' status) -like "*Available for this process: True*")) {
		$env:GsudoCache="1"
	} else {
		$env:GsudoCache=""
	}	
}

New-Alias -Name 'Set-PoshContext' -Value 'Set-MyPoshContext' -Scope Global -Force
```

And this is how my segment looks:

```
    {
      "alignment": "left",
      "newline": true,
      "segments": [  
        {
          "foreground": "#B48EAD",
          "foreground_templates": [
            "{{ if .Env.GsudoCache}}#FFFFFF{{ end }}"
          ],
          "properties": {
            "always_enabled": true
          },
          "style": "plain",
          "template": "{{ if .Root }}# {{else}}\u276f {{end}}",
          "type": "text"
        }
      ],
      "type": "prompt"
    },
```
And the transient mode:
```
     "transient_prompt": {
    "foreground": "#B48EAD",
    "foreground_templates": [
      "{{ if gt .Code 0 }}#BF616A{{ end }}"
    ],

```

**Comment by gerardog** [comment]
Have you tried it? it works for me. I will close the issue. Feel free to reopen if you find any problem. Thanks
