### ISSUE TITLE
RunAsUser

### ISSUE THREAD

**Issue by dhirschfeld** [gerardog/gsudo#22]
If my normal account isn't an admin can I pass administrator credentials (username/password) to use?

I see [some mention](https://github.com/gerardog/gsudo/blob/9cee796464b3ad177df5c0d4f54f794c75290362/backlog.md#L11) of this in `backlod.md` but I'm not sure it's implemented yet?

**Comment by gerardog** [comment]
Yes, this is working since #4 that was addressed in v0.5.1.
But only works, as you said, if the user is NOT admin.

If you were admin, currently justs shows the regular UAC popup (Yes/No), and does not prompts for user and password. So you can only elevate as the current (admin) user. That could change in the future. 

Sorry about the `backlog.md` it is outdated and my mention there was about the RunAsUser Verb that would allow to specify any user... Right now gsudo only uses RunAs verb, that sometimes limits the `Username` field).

![runas](https://user-images.githubusercontent.com/3901474/74498310-f3d81980-4ebe-11ea-9f34-7ad2660b95ef.gif)

**Comment by dhirschfeld** [comment]
Awesome, thanks - I'll give it a go!

If my user is admin I'm fine with using that account I was just concerned that I might not be able to use it without being admin (despite having a separate admin account)

**Comment by fiasko** [comment]
Could you please revisit this issue? RunAsUser would be much apreciated. I'm currently in a situtation where I have to use secondary user account only for admin tasks only. It would help a lot if I could define the user account under which the elevetaion is done in gsudo call.

**Comment by gerardog** [comment]
Hi @fiasko. 
If the current user is not admin, it asks for admin credentials, and you can put your secondary user account, as shown in the video above. Doesn´t that work for you? If so, why?

**Comment by Ghoul-Kun** [comment]
UnsubscribeOn May 13, 2022 18:37, Gerardo Grignoli ***@***.***> wrote:

Hi @fiasko.

If the current user is not admin, it asks for admin credentials, and you can put your secondary user account, as shown in the video above. Doesn´t that work for you? If so, why?

**Comment by fiasko** [comment]
Well, yes it opens the UAC popup. But in my case it requires several clicks and lots of typing to navigate through every time. First from the UAC popup I need select "another user" option (with mouse), then I need to type the username (which is not very short in this case), then hit tab/click password field, and type a password (which has minimum length requirement of 15 characters including numers, big letters and small letters). This is the process that I have to do at least once a day. Usually several times a day. I'm not saying that it can't be done. All I'm sayig is that if it's possible to get any of these steps removed, it would help **a lot**.
Thanks for noticing my reply. If by any change you can do anything about it, I would be very happy. Not that I'm not happy already with the gsudo. But still there seems to be more room for additional hapiness 😄
