### ISSUE TITLE
Issue: CacheMode Auto not working when intalled with scoop and using sudo alias

### ISSUE THREAD

**Issue by ssxwcz** [gerardog/gsudo#237]
## Issue Description

Same as https://github.com/gerardog/gsudo/issues/98 problem .
I installed it using scoop install gsudo. The Credentials cache cannot be enabled after executing 'sudo ls', but the Credentials cache can be enabled normally after executing' gsudo ls'.
## Steps to Reproduce

1.  Set config option to set cache to auto.
2. Restart Windows Terminal
3. Try testing out sudo persistence, it asks for elevation on every command

## Screenshots 

![image](https://user-images.githubusercontent.com/43665491/221797880-ff51b1f6-cb72-431e-b52a-4d6a59b25f84.png)
![image](https://user-images.githubusercontent.com/43665491/221797026-04de731c-6e85-4460-ba34-9219520c3f3e.png)
![image](https://user-images.githubusercontent.com/43665491/221795879-2c1ed54f-1d75-418a-bcb0-c6ab9ac11d92.png)

## Context:
  - Windows version: Win11 22H2 (22623.1037)

 - gsudo version:
    ```
    gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)
    Copyright(c) 2019-2022 Gerardo Grignoli and GitHub contributors
    ```

**Comment by gerardog** [comment]
* When you install using scoop
* You are using either cmd or pwsh
* You have CacheMode=auto, and your cache is off
* You use the sudo alias (which is a `sudo.exe` shim file generated by scoop at `C:\Users\XX\scoop\shims\sudo.exe`)

Then yes, the caller pid is process is incorrectly identified. Its taking the shim, not the shim caller. 

In this image, caller pid should say 23940 instead of 22044:
![image](https://user-images.githubusercontent.com/43665491/221797026-04de731c-6e85-4460-ba34-9219520c3f3e.png)

**Comment by gerardog** [comment]
You can test a preview build if you scroll down to artifacts:
https://github.com/gerardog/gsudo/actions/runs/4310206577

**Comment by ssxwcz** [comment]
> You can test a preview build if you scroll down to artifacts: https://github.com/gerardog/gsudo/actions/runs/4310206577

Yes, the issue has been fixed, thanks a lot
![image](https://user-images.githubusercontent.com/43665491/222323348-793f2fe8-0dd6-4087-8518-f973485743cd.png)
