### ISSUE TITLE
Issue: "Current" folder not created when installing with winget

### ISSUE THREAD

**Issue by AkazaRenn** [gerardog/gsudo#250]
## Issue Description

By installing from `winget`, the `C:\Program Files\gsudo\Current` is added to the path but this folder does not exist, causing an extra manual step to resolve the path.

## Steps to Reproduce

1.  In an elevated terminal, run `winget install gerardog.gsudo`
2.  Check the System Environment Variables to confirm `C:\Program Files\gsudo\Current` is added to `Path`
3.  Check `C:\Program Files\gsudo\Current` does not actually exist

## Screenshots 

![image](https://user-images.githubusercontent.com/8340896/231267488-990bec0c-4fd7-4ac9-95ca-83cd3de464e9.png)
![image](https://user-images.githubusercontent.com/8340896/231267543-ecc27547-4ba6-421a-8094-9742e7d1a292.png)

## Context:
  - Windows version: Windows 11 22H2 22621.1413 - English (US)

**Comment by gerardog** [comment]
`gsudo\Current` should be a junction to `gsudo\2.0.6`
![image](https://user-images.githubusercontent.com/3901474/231276379-09880057-adfb-4987-a245-4e1d1f7ff29b.png)

could you please run:
```
cmd /c mklink /J "C:\Program Files\gsudo\Current_but_testing" "C:\Program Files\gsudo\2.0.6"
```
... as admin (or if your gsudo is working, prepend gsudo)
an let me know if it creates "Current_but_testing", please?

**Comment by hj0x3** [comment]
Ran into this issue myself, installing gsudo 2.0.9 via winget (technically, updating to 2.0.9 from 2.0.6).  After it updated, `gsudo` command was no longer being recognized, and saw it was due to the `Current` link not being created.

![image](https://github.com/gerardog/gsudo/assets/665915/0a458139-f169-4649-bf64-f9a100bf2f09)

Ran `mklink` as requested, and confirmed the link was successfully created.

`cmd /c mklink /J "C:\Program Files\gsudo\Current_but_testing" "C:\Program Files\gsudo\2.0.9"`

![image](https://github.com/gerardog/gsudo/assets/665915/1f44149b-7bda-4762-9d94-fdce3dd2b810)

Uninstalled gusdo, then installed via running the msi package directly. The `Current` link was created as part of the installation as expected.
