### ISSUE TITLE
Single executable

### ISSUE THREAD

**Issue by bvarnai** [gerardog/gsudo#26]
Maybe it would be nice to have a single executable with dependencies statically linked. It might be around 50-60mb but I don't think that is an issue for the users. Just as additional distribution. Thanks!

**Comment by gerardog** [comment]
Hi bvarnai.

This can be done. But first, let me ask you: Did you have to install something to make it work? Do you find it convenient to be a single file? Why?

The current packaging logic is to target .Net 4.6 because  [`"Windows 10 (all editions) includes the .NET Framework 4.6 as an OS component, and it is installed by default"`](https://docs.microsoft.com/en-us/archive/blogs/astebner/mailbag-what-version-of-the-net-framework-is-included-in-what-version-of-the-os)

And, I wasn't really interested in supporting anything older than W10.
Therefore I the package size is small, and should work without installing a any dep.
It's not a single file, but can be deployed with copy/paste in W10, so it could be said it is 'portable'.

**Comment by gerardog** [comment]
This seems to do the trick...
``` batch
choco install ilmerge
ilmerge gsudo.exe System.Security.Claims.dll System.Security.Principal.Windows.dll /out:gsudoPortable.exe /target:exe /targetplatform:v4,"C:\Windows\Microsoft.NET\Framework\v4.0.30319"
```
... before signing the assembly.

Final file size is around the sum of all input files. 
I can include this in the next release. I can't think of any drawback, but haven't tested it.

**Comment by bvarnai** [comment]
Hi gerardog!

Thanks for the feedback!

Sorry, "no-dep" was misleading, there are no missing external dependencies, everything works fine. What I meant to have a single executable without the dlls etc. IMO it's easier to handle from the user perspective. You proposal using "ilmerge" seems to be a perfect solution.

BTW the tool is awesome! We have a bunch of DevOps related bash scripts under Windows, it was a mess to run things elevated, getting stdout or errorlevel was a pain. Now it's just works.
