### ISSUE TITLE
Running gsudo from mapped drive

### ISSUE THREAD

**Issue by lazna** [gerardog/gsudo#27]
Have script utilizing gsudo.exe saved on my network storage, mapped as a drive Z: Starting script from Z:\, script working successfully but gsido failed with following message:

```
gsudo --raw --debug netsh interface ipv4 set address "UGHGH" static 10.12.15.3 255.255.255.224 10.12.15.1
Debug: IsWindowsApp("C:\WINDOWS\system32\netsh.EXE") = False ("C:\WINDOWS\system32\netsh.EXE")
Debug: Application to run: C:\WINDOWS\system32\netsh.EXE
Debug: Arguments: interface ipv4 set address "UGHGH" static 10.12.15.3 255.255.255.224 10.12.15.1
Debug: Using Console mode Raw
Debug: Caller ProcessId is 2188
Debug: Connected via Named Pipe gsudo_S-1-5-21-2888163432-2796349975-2356466950-1001_2188.
Debug: ElevationRequest length 631
Server Error: System.ComponentModel.Win32Exception (0x80004005): The directory name is invalid
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at gsudo.Helpers.ProcessFactory.StartInProcessRedirected(String fileName, String arguments, String startFolder)
   at gsudo.ProcessHosts.PipedProcessHost.<Start>d__3.MoveNext()
Warning: Connection from server lost.
```
Is it because of elevated users 'Administrator' profile does not have mapped such drive? Is there any workaround for such situations, or could there be a specific errromessage and related exitcode for this case?

**Comment by gerardog** [comment]
Yes, the elevated and non-elevated apps are actually running in isolated logon sessions, with isolated network connections each. Therefore UNC paths (`\\server\share\file`) may not be accesible if the elevated session doesn't inherit access or has cached credentials for that share.
Also, mapped drives are no longer resolvable from the elevated session, for instance: If you run `gsudo` and your current directory is a mapped drive like `Z:` when elevated the `Z:` drive no longer points us to a valid `\\server\share\file` path. 

This two issues breaks two things:
* One anti-tampering gsudo protection method.
* The current directory may be invalid on the elevated session, so many commands will refuse to run.

So, this issue is non trivial to solve and has ramifications.

Nonetheless, I've managed to make some fix that allows to use gsudo from a mapped or network drive as long as the **current directory** is NOT a network drive.

For example the following cases are working on my machine after some fixing
```
C:\> Z:\utils\gsudo.exe netsh interface ipv4 set ...
C:\> \\server\share\gsudo netsh interface ipv4 set ...
```
(please note the current directory is C:, not z: )

You can preview the fix from this [**UNSTABLE**, unsigned build](https://ci.appveyor.com/project/gerardog/gsudo/builds/31630180/artifacts)) 

Another workaround would be to copy `gsudo` to a local folder first...
As a sidenote, you may want to omit the `--piped` argument and let gsudo decide which mode to use.

**Comment by gerardog** [comment]
I've done some tests with v0.7 and, in my extremely limited network/scenario, looks like it's working.
I appreciate anyone who can jump in and let me know if this is still and issue.
Thanks.-
