### ISSUE TITLE
Feature Request: Add PowerShell cmdlet

### ISSUE THREAD

**Issue by soroshsabz** [gerardog/gsudo#279]
ITNOA

## Description
I think it is good to add PowerShell style cmdlet alias for `gsudo`, for example `RunAs-Administrator` or `Invoke-ElevatedCommand`

**Comment by gerardog** [comment]
Hi ! 
Please take a careful read at [powershell usage readme](https://github.com/gerardog/gsudo/#usage-from-powershell--powershell-core).

If you run `Import-Module gsudoModule` you have syntax autocomplete for gsudo, which kind of eliminates the need for a native function.

I also created `Invoke-gsudo` wrapper for gsudo a lot time ago and is still included in the Powershell module. I almost branded it as 'Invoke-ElevatedCommand'. (The conversation in #39 If you are interested in archeology ) But later found how to leverage powershell's native console serialization, which is waaaay much faster. It is so much better that I am considering declaring Invoke-gsudo as deprecated.

**Comment by soroshsabz** [comment]
@gerardog I think I do not understand correctly, (I do not find `Invoke-ElevatedCommand` in #39 and in this repo) and my note is `Invoke-gsudo` is not good PowerShell style cmdlet, **So I suggest add `Invoke-ElevatedCommand` into PowerShell Module**.

About wrapping native application, I think https://devblogs.microsoft.com/powershell/native-commands-in-powershell-a-new-approach/ has good approach

**Comment by gerardog** [comment]
What does ITNOA means?
What feature would you be looking for in a `Invoke-ElevatedCommand` and why?
Do you understand that `Invoke-Command` runs in the same process (unless `-Computer` or `-SessionName` is used) which allows accesing `$variables` but on the other hand gsudo runs scripts in a different elevated process so it can't ?

Also Invoke-gsudo focused on using the `$using:` syntax sugar which `Invoke-*` instead of the `-args`.

I need you to do three things please:
1. Carefully answer the above questions and provide as much context and detail as possible.
2. Try this script for an give me your feedback. Create an `Invoke-ElevatedCommand.ps1` 

``` powershell
<#
.SYNOPSIS
Executes a ScriptBlock or script file in a new elevated instance of PowerShell using gsudo.

.DESCRIPTION
The Invoke-ElevatedCommand cmdlet serializes a ScriptBlock or script file and executes it in an elevated PowerShell instance using gsudo. The elevated command runs in a separate process, which means it cannot directly access or modify variables from the invoking scope. 

The cmdlet supports passing arguments to the ScriptBlock or script file using the -ArgumentList parameter, which can be accessed with the $args automatic variable within the ScriptBlock or script file. Additionally, you can provide input from the pipeline using $Input, which will be serialized and made available within the elevated execution context.

The result of the elevated command is serialized, sent back to the non-elevated instance, deserialized, and returned. This means object graphs are recreated as PSObjects.

Optionally, you can check for "$LastExitCode -eq 999" to determine if gsudo failed to elevate, such as when the UAC popup is cancelled.

.PARAMETER ScriptBlock
Specifies a ScriptBlock to be executed in an elevated PowerShell instance. For example: { Get-Process Notepad }

.PARAMETER ArgumentList
Provides a list of elements that will be accessible inside the ScriptBlock or script as $args[0], $args[1], and so on.

.PARAMETER LoadProfile
Loads the user profile in the elevated PowerShell instance, regardless of the gsudo configuration setting PowerShellLoadProfile.

.INPUTS
You can pipe any object to this function. The object will be serialized and available as $Input within the ScriptBlock or script.

.OUTPUTS
The output of the ScriptBlock or script executed in the elevated context.

.EXAMPLE
PS> Get-Process notepad | Invoke-ElevatedCommand { Stop-Process }

PS> Invoke-ElevatedCommand { return Get-Content 'C:\My Secret Folder\My Secret.txt' }

PS> $a = 1; $b = Invoke-ElevatedCommand { $using:a + 10 }; Write-Host "Sum returned: $b"
Sum returned: 11

.LINK
https://github.com/gerardog/gsudo
#>
[CmdletBinding(DefaultParameterSetName = 'None')]
param
(
    # The script block to execute in an elevated context.
    [Parameter(Mandatory = $false, Position = 0)] [System.Management.Automation.ScriptBlock] $ScriptBlock,

##.PARAMETER FilePath
##Specifies the path to a script file to be executed in an elevated PowerShell instance.
##    [Parameter(Mandatory = $false)] [String] $FilePath,

    # Optional argument list for the program or the script block.
    [Parameter(Mandatory = $false, Position = 1)] [System.Object[]] $ArgumentList,

    [Parameter(ValueFromPipeline)] [pscustomobject] $InputObject,
	[Parameter()] [switch] $LoadProfile = $null,
	[Parameter()] [switch] $RunAsTrustedInstaller,
	[Parameter()] [switch] $RunAsSystem,
	[Parameter()] [switch] $ClearCache,
	
	[Parameter()] [switch] $NewWindow,
	[Parameter()] [switch] $KeepNewWindowOpen,
	[Parameter()] [switch] $KeepShell,
	[Parameter()] [switch] $NoKeep
)

$gsudoArgs = @()

if ($PSCmdlet.MyInvocation.BoundParameters["Debug"].IsPresent) { $gsudoArgs += '--debug' }

if ($LoadProfile)	{ $gsudoArgs += '--LoadProfile' }
if ($RunAsTrustedInstaller)	{ $gsudoArgs += '--ti' }
if ($RunAsSystem)	{ $gsudoArgs += '-s' }
if ($ClearCache)	{ $gsudoArgs += '-k' }
if ($NewWindow)		{ $gsudoArgs += '-n' }
if ($KeepNewWindowOpen)		{ $gsudoArgs += '--KeepWindow' }
if ($KeepShell)		{ $gsudoArgs += '--KeepShell' }
if ($NoKeep)		{ $gsudoArgs += '--close' }

if ($LoadProfile -eq $false) { 
	# Get pwsh.exe filename
	if ($host.Name -match 'consolehost') { # Workaround for PowerShell ISE, or PS hosted inside other process
		if ($PSVersionTable.PSVersion.Major -le 5) 
			{ $pwsh = "powershell.exe" } 
		else 
			{ $pwsh = "pwsh.exe" }
	} else {
		$pwsh = ("$([System.Diagnostics.Process]::GetCurrentProcess().MainModule.FileName)") # Get same running powershell EXE.
	}

	$gsudoArgs += '-d';
	$gsudoArgs += $pwsh;
	$gsudoArgs += '-NoProfile';
	$gsudoArgs += '-NoLogo';
}

if ($InputObject -ne $null)
{
	$InputObject | gsudo.exe @gsudoArgs $ScriptBlock -args $ArgumentList
} else {
	gsudo.exe @gsudoArgs $ScriptBlock -args $ArgumentList
}
```

4. See if you can spot why the CmdLetBinding is just streaming the first element of the input to native app. (In the screenshot I named the above code as test.ps1). This is one case where the function wrapper degrades the experience compared to using gsudo.

![image](https://github.com/gerardog/gsudo/assets/3901474/932dfcb2-dca0-4985-9bb8-62788c8cb832)

**Comment by gerardog** [comment]
As the moderator for this GitHub repository, I've decided to close this issue due to the use of the phrase "ITNOA", short for "In The Name Of Allah". While I fully respect and understand that this is a phrase of significance in Islam and may be a reflection of personal beliefs, GitHub is a platform for collaboration on software development. It's crucial to maintain a secular and inclusive environment here that is comfortable for people of all beliefs, cultures, and backgrounds.

Using religious language, regardless of the religion, can be distracting and may potentially make some community members uncomfortable. This is not about singling out a particular belief system, but about upholding a neutral space where everyone can focus on the shared goal of software development. Thank you for your understanding, and I look forward to continuing to work with you on other issues and contributions that adhere to these guidelines.
