### ISSUE TITLE
gsudo --vt seems to have problems with character encoding

### ISSUE THREAD

**Issue by oising** [gerardog/gsudo#31]
First up, great work Gerardo. Superb, in fact. Now, on to the issue at hand:

![image](https://user-images.githubusercontent.com/1844001/80920807-3f70c580-8d40-11ea-9e2f-30012934eef9.png)

As you can see, `gsudo` without conpty is fine. But with `--vt` for conpty, the extended unicode characters are getting corrupted/munged somehow. I don't think this is an issue with conpty since WT itself uses conpty in general, and unicode works fine (obviously.)

Let me know if you need any more information. I'm using Fira Code as a font.

**Comment by gerardog** [comment]
> First up, great work Gerardo. Superb, in fact. 

Thanks, I appreciate it!

> As you can see, gsudo without conpty is fine. But with --vt for conpty, the extended unicode characters are getting corrupted/munged somehow. 

I haven't yet found time to find the root cause. `gsudo` uses Utf-8 which is unicode with 8 bytes representation. So, it should support all characters, right? There is a hidden problem somewhere and I should investigate, but nonetheless when I [switched](https://github.com/gerardog/gsudo/commit/127acbf1dc89da341e8cd130d1f645a05d6fa1bd) all IPC encodings to Utf-16 the problem is gone. 

So, in case you want a fast-fix try [this unsigned build](https://ci.appveyor.com/project/gerardog/gsudo/builds/32633110). 

But I am very courious on why are you using the VT/Pseudoconsole mode. It was my first approach to gsudo, and it has never been very reliable. I quickly ran into microsoft/terminal#3765 which Microsoft is not responding and my [workaroud](https://github.com/microsoft/terminal/issues/3765#issuecomment-566752685) was flagged as "A non-recommended way to fix this issue that will cause long-term application stability issues", LOL. ConHost may wrap VT sequences at the far right of the screen, breaking them. So... I've marked VT mode as deprecated and almost deleted it's code. Let me know please!

**Comment by oising** [comment]
It might be related to the lack of a ConPTY passthrough mode, the goal being to let all VT generated by client apps be unmolested by the plumbing: https://github.com/microsoft/terminal/issues/1173

**Comment by oising** [comment]
Closing as VT mode is deprecated.

**Comment by gerardog** [comment]
I got an answer on microsoft/terminal#3765. It was a silly mistake on my end. So I started looking into this:

The real issue here is this is missing line:
`Console.OutputEncoding = System.Text.Encoding.UTF8;`
Without it, it won't print the unicode symbols, like the special ">" as in `Console.WriteLine("\ue0a0");`
