### ISSUE TITLE
Warnings using gsudo with Google Drive FS

### ISSUE THREAD

**Issue by kotasher** [gerardog/gsudo#32]
Using latest gsudo and Google Drive FS both installed via chocolatey packages and each time I type "sudo ..." there are warnings mentioned on attached screenshot.

gsudo v0.7.0
google-drive-file-stream v38.0.16.0

![image](https://user-images.githubusercontent.com/16614508/81792423-b7917500-9510-11ea-9071-698462fe8845.png)

**Comment by gerardog** [comment]
Hi kotasher,
Certainly it's not `gsudo` writing those warnings. It's probably GDFS running into an internal issue. Probably `gsudo` is just trying to read a GDFS folder.

I installed GDFS on a VM, and I was not able to reproduce this issue. 

* The `Error: The operation was canceled by the user` is just because you clicked on `no` on the UAC popup, right?
* Whats the outcome if you use 'gsudo' instead of 'sudo'? also use `gsudo --debug cup all` for more detailed info please.
* Whats the output of `where sudo` in cmd? the resulting folder is a local HDD folder or a gdfs path?
* Do you have any network or GDFS folder included in the path environment variable?
* Were you able to reproduce the issue even after a restart? I am suspecting a connectivity issue?

It would be perfect if you had a clean VM around so you could send me the steps to setup a repro environment for this issue... As I said, `choco install gsudo` + `google-drive-file-stream` connected to my account wasnt enough to make those warnings appear.

Thanks

**Comment by kotasher** [comment]
> The Error: The operation was canceled by the user is just because you clicked on no on the UAC popup, right?

Absolutely right. It is not the problem.

> Whats the outcome if you use 'gsudo' instead of 'sudo'? also use gsudo --debug cup all for more detailed info please.

By the way, gsudo works like a charm, here is the screenshot.
![image](https://user-images.githubusercontent.com/16614508/81903620-adcc4800-95ca-11ea-9a66-1de48ae50809.png)

> Whats the output of where sudo in cmd? the resulting folder is a local HDD folder or a gdfs path?

![image](https://user-images.githubusercontent.com/16614508/81903720-d5231500-95ca-11ea-9f05-636ae23dec26.png)

> Do you have any network or GDFS folder included in the path environment variable?

No network or GDFS folder included as far as I see.

> Were you able to reproduce the issue even after a restart? I am suspecting a connectivity issue?

Perfectly reproducible each time using "sudo" command but not "gsudo".


> It would be perfect if you had a clean VM around so you could send me the steps to setup a repro environment for this issue... As I said, choco install gsudo + google-drive-file-stream connected to my account wasnt enough to make those warnings appear.

Unfortunatelly, right now I have no time to investigate it more, maybe some time later.

**Comment by gerardog** [comment]
That's very informative, thanks.

So what I got is: 
* this is related to the `sudo` symbolic link
* it's happening after `Debug: Elevating Process` and before the cancelled exception, so it is in [this method](https://github.com/gerardog/gsudo/blob/e5bc92124ad6fef97b49e8223e6ee6a0886d2379/src/gsudo/Helpers/ProcessFactory.cs#L22)
* so, the warning is written inside .NET Process.Start method (with RunAs Verb) which is a .NET/Windows OS area, probably then inside some GDFS hooked code...  

* this is more likely a GDFS problem triggered when doing RunAs on a SymLink, which is not a very common scenario. It may be worth to report to google. You might be able to reproduce this by running this from a non-elevated powershell: `Start-Process -verb RunAs Sudo -ArgumentList "cup all"`.. In my setup it's not, but if in you computer it does the warnings, then you could create another symlink, like `cmd /c mklink NotepadSymLink.exe C:\windows\notepad.exe` and then  `Start-Process -verb RunAs NotePadSymLink`, that, if it warns, is a non-gsudo-repro-case to report to google team.

Nonetheless, `gsudo` should have detected the symlink and tried to elevate the `gsudo` exe instead of the `sudo` symlink. That is something I can fix and should probably eliminate the warnings.

**Comment by gerardog** [comment]
I was able to reproduce this problem locally, I think because after a while I am now logged off. Will confirm you if the warnings are gone after the fix.
