### ISSUE TITLE
Issue: sudo alias (sudo !!) throws a ParseError exception and doesn't elevate the last executed command in PowerShell Core

### ISSUE THREAD

**Issue by gpshonik** [gerardog/gsudo#329]
## Issue Description
In PowerShell Core (currently on v7.4.1), running the `sudo` alias `sudo !!` throws a `ParseError` exception and doesn't elevate the last executed command in PowerShell Core

## Steps to Reproduce

1. In Pwsh, run any command that requires elevation
2. run `sudo !!` 
3. After accepting the UAC prompt, PowerShell Core throws a `ParserError` exception

<img width="1181" alt="image" src="https://github.com/gerardog/gsudo/assets/1524361/dc3781f3-c830-49e5-9323-6b67701d8890">

note:  `sudo !!` works as expected under the CMD shell

## Context:
  - Windows version: 23H2
  - gsudo version:   gsudo v2.4.2

**Comment by gerardog** [comment]
Hi @gpshonik!

- Could you run `Get-Command sudo` and check the results? On a default install it should point to `sudo.exe`. If it is pointing to a `sudo` function, it is highly likely a custom function you created that is generating that Parser Error, and you will have to delete it.

- Out of the box, this is the experience you should be having:
![image](https://github.com/gerardog/gsudo/assets/3901474/6499abe9-0ead-4b4f-b32f-38412b0ebf64)
 
- As shown in the image `sudo !!` doesnt work. `sudo` is not aliased to `gsudo`. In the powershell world, utilities or modules tend not to create custom aliases in behalf of the user, because it means editing your `$PROFILE` file, usually at `C:\Users\your-username\Documents\PowerShell\Microsoft.PowerShell_profile.ps1`. gsudo respects that, therefore does not creates an alias `gsudo -> sudo`. 

- You should create the alias yourself by adding this line to your `$PROFILE` file: `Set-Alias sudo -Value gsudo`, preferably after `Import-Module gsudoModule`. (After deleting your custom sudo function)

![image](https://github.com/gerardog/gsudo/assets/3901474/70aa3b50-a8d6-4e05-a956-36cf417de194)

Regards.-

**Comment by gpshonik** [comment]
Thank you for the detailed response. I feel very silly now because I did indeed have a custom sudo.ps1 in my path that had higher precedence than gsudo/sudo. 🤦‍♂️

After removing sudo.ps1, the behavior is exactly as you describe. After adding a custom alias in `$PROFILE` the behavior is exactly what I was after. 

Thanks again for this great utility and for taking the time to write a detailed response.  Apologies for wasting your time and I will close out the issue now.

**Comment by gerardog** [comment]
Don't feel silly at all bro in this constantly learning journey! The only reason the answer came to me so fast (not wasted time, really) is that I did the exact same thing once before. And only the PowerShell folks thought me the way. Here is the [proof](https://github.com/PowerShell/PowerShell/issues/17031#issuecomment-1072919176)!  :) Have a great day.
