### ISSUE TITLE
Cannot call the function defined in profile 

### ISSUE THREAD

**Issue by potoo0** [gerardog/gsudo#33]
Function defined in Global Profile(`C:\Windows\System32\WindowsPowerShell\v1.0\profile.ps1`):
```powershell
Function TestUserFunc
{
    echo 'Function defined in Global Profile'
}
```

Call user function with sudo will rasie *ObjectNotFound*(shown in figure 1):
![image](https://user-images.githubusercontent.com/34411681/82447450-e7c1b080-9ada-11ea-9ae9-d629afc21021.png)

**Comment by gerardog** [comment]
Here is the dilema: In #10 the exact opposite was requested: to not to load the profile when elevating commands. (And only load it when elevating the shell as in simple `gsudo` call withouy) It makes sense to me because in my experience loading the profile takes a lot of time and is not usually required.

There is no single solution that would fit both workflows. So, should I make this configurable? There is some complexity to support each Powershell version, that makes the configurability 'heavy'. Maybe something like `gsudo config LoadPsProfile Never/NoCommand/Always'. I have to give it a thought.

As a workaround, you could do:
* `gsudo Powershell -NoLogo -Command TestUserFunc`
* or elevate the shell with `gsudo` then run `TestUserFunc`
* export the function to a TestUserFunc.ps1 that is in the user path

**Comment by potoo0** [comment]
OK, got it, thx.

**Comment by mitranim** [comment]
Just had a similar issue. Thanks for posting a solution. For anyone having similar issues, you can make this easy to invoke by adding a function to your profile, something like:

```ps1
function sudops {
  sudo powershell -nologo -command @args
}
```
