### ISSUE TITLE
Issue: Sophos AV blocks gsudo

### ISSUE THREAD

**Issue by bh-chwo** [gerardog/gsudo#347]
## Issue Description

I tried upgrading some apps with winget, but my Sophos AV instantly blocked the function and isolates the PC.

## Steps to Reproduce

1.  powershell
2. gsudo winget upgrade
3. PC is isolated

## Screenshots 

![Screenshot 2024-04-25 115125](https://github.com/gerardog/gsudo/assets/77726336/d38dee73-557f-4f53-883a-6db42840b4c1)

```powershell
gsudo --debug winget upgrade
Debug: Invoking Shell: PowerShellCore
Debug: Command Line: --debug winget upgrade
Debug: Command to run: "C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -Command "winget upgrade"
Debug: Using Console mode TokenSwitch
Debug: Caller PID: 15432
Debug: Connected via Named Pipe ProtectedPrefix\Administrators\gsudo_DF763A2E0FF2D26118E29D84696CBBF5EB5C619350AB009D1B0B680D6A5ECDE8.
Debug: Creating target process: "C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -Command "winget upgrade"
Debug: Process token successfully substituted.
Debug: Process exited with code 0
```

## Context:
  - Windows version:
 
Version 22H2 (Build 22621.3447) - German
  - gsudo version:      

gsudo v2.4.4 (Branch.tags-v2.4.4.Sha.cf887bf98d5d3d90fc1eebc08c7a277afb50cd19)
Copyright(c) 2019-2022 Gerardo Grignoli and GitHub contributors

**Comment by gerardog** [comment]
Sophos Antivirus is mistakenly flagging gsudo as a potential threat. Unfortunately, this type of issue falls under the antivirus software's responsibility, as false positives can occur with certain tools or scripts.

Please report this to Sophos so they can investigate and whitelist gsudo if appropriate. In the meantime, you could also try adding an exclusion in Sophos for gsudo, if possible, to prevent it from being blocked.

**Comment by wschlich** [comment]
The issue is **not** Sophos blocking `gsudo` _itself_, as the following works just fine inside a non-elevated PS7 session:
```
gsudo { Get-ComputerInfo; };
```

Running...
```
gsudo notepad
```
...instead leads to the blockage.

This might help:

Sophos KBA-000010216:
[Sophos Central: Prevent access token manipulation feature blocks a low-privilege process from gaining higher privileges](https://support.sophos.com/support/s/article/KBA-000010216)

> As of January 2025, the Threat Protection policy was updated to allow more granular control over the PrivGuard functionality. The PrivGuard feature Prevent access token manipulation can now be turned off on devices running Sophos Core Agent 2024.3 and later to turn off a sub-component of PrivGuard, making it compatible with PAM software while retaining all other PrivGuard functionality.

The setting `Prevent access token manipulation` can be found in Sophos Central inside the settings of the `Threat Protection` policy (which is currently active for the corresponding computer) in the section `Runtime Protection` below `Protect processes` and there under `Prevent privilege escalation`.

As an alternative, one can go to a matching detection event in Sophos Central (listed under the corresponding computer at `https://central.sophos.com/manage/overview/computers-list/<GUID}/events` -- you can get there via https://central.sophos.com/manage/endpoint/devices-list). Look for events like `Access token manipulation exploit prevented in C:\Program Files\PowerShell\7\pwsh.exe` and `Access token manipulation exploit prevented in C:\Windows\System32\cmd.exe`. Then, for each different event, click on `Details`, activate `Exclude this Detection ID from checking`, enter an exclusion comment as you like and click on `Exclude` (you can then find these exclusions under https://central.sophos.com/manage/endpoint/settings-list/scanning-exclusions). I'm not sure whether excluding these 2 specific event IDs is the preferable solution tbh, so please consider for yourself which way you prefer. 

Cheers,
Wolfram

**Comment by bh-chwo** [comment]
Thank for the clarification, but I believe since 23H2 there is a developer switch in Windows to activate sudo. And it works like gsudo.
