### ISSUE TITLE
how to remove gsudo 

### ISSUE THREAD

**Issue by shuohao** [gerardog/gsudo#37]
windows 10 powershell

**Comment by gerardog** [comment]
Sorry to see you go... If you want to leave feedback, you can ping me on twitter.

`gsudo` is a portable app so uninstalling means to delete the files and remove gsudo directory from the user PATH environment variable. In order to get that done:

If you installed using Scoop, do: `scoop uninstall gsudo`
If you installed using Chocolatey, do: `choco uninstall gsudo`
If you installed using the manual installation powershell file, open PowerShell then:

``` powershell
# Terminate gsudo instances, just in case
tskill gsudo

$destdir = "$home\apps\gsudo"
# Remove gsudo files
rmdir $destdir -r

# Remove gsudo folder from PATH
$p = [System.Environment]::GetEnvironmentVariable('Path', [System.EnvironmentVariableTarget]::User).Replace(";$destdir", "");
[System.Environment]::SetEnvironmentVariable('Path',$p,[System.EnvironmentVariableTarget]::User);
```
