### ISSUE TITLE
"L" key targets active gsudo window during runtime

### ISSUE THREAD

**Issue by itshoro** [gerardog/gsudo#58]
Hey, when using gsudo the "L" key (lower case L to be exact) becomes unresponsive and instead targets the active gsudo instance.
This is especially troublesome, when trying to spawn a powershell or running chocolatey.

Repro:
1.1) Open Windows Search or the Run Dialog
1.2) Type in for example `sudo powershell`
1.3) Select the command invoke (only applicable for Windows Search)
1.4) A gsudo window with powershell running will now open
1.5) Select another window or collapse the gsudo window
1.6) Press only the "L"-Key (Note: Shift + L doesn't trigger the problem)
1.7) The key doesn't produce an output and instead pulls focus to the gsudo instance
1.8) Close the gsudo instance
1.9) L-key now works as intended again.

It seems to have something to do with running these applications embeded within gsudo, as when the `-n` parameter to spawn a new window is passed the "L" key works as intended.

Windows 10 version 2004
Gsudo Version 0.7.2 (Installed via chocolatey)

**Comment by gerardog** [comment]
Hi, thanks for reporting your issue.

I've tried your steps with no luck, I'm not able to reproduce this behaviour. 
gsudo has no code to hook-up keys on a system level, at least intentionally.

Were you able to reproduce this after a reboot or on another computer?
Another thing to test would be if your console shortcut has any shortcut-key defined:

![image](https://user-images.githubusercontent.com/3901474/93081685-050c2300-f666-11ea-9b01-1647e8056d7a.png)
![image](https://user-images.githubusercontent.com/3901474/93081769-2967ff80-f666-11ea-9634-f76821304403.png)

Or else, do you have any special app that does key bindings? such as PowerToys, AutoHotkey, etc?
Does this happens with "gsudo cmd"?

**Comment by itshoro** [comment]
Yes it happens both on my Surface Book 1 and my Desktop PC (both Windows 10 2004), I had this issue for a while now, but only now decided to open an issue, as it started to annoy me. 😅

So the issue persists through restarts for me. I do use PowerToys and ShareX that implement global hotkeys, but this issue still is present for me when both of them are closed.

This also applies to `gsudo cmd` or `gsudo choco upgrade all -y` for example.

As you can see I also don't have any shortcuts setup.
![image](https://user-images.githubusercontent.com/15874697/93083041-3dc1f180-f692-11ea-968a-825ee9cbfb71.png)

I do have powerline setup for powershell, but this shouldn't impact anything as cmd also can reproduce my problems, with powerline not present there.

Here a video showing the issue in action, I sadly don't have anything setup to show you the keystrokes. :/ https://www.youtube.com/watch?v=uSRaGJdmQ88

I noticed that I can write a lower-case L in the console by using `Alt + L`, but I don't think this works as intended.

Do you have any other idea, or information I can send you?

**Comment by gerardog** [comment]
That's weird. 

Test to see if this is related to the sudo alias:
Does this happens if you use gsudo instead of sudo?

Test to see if this is related to gsudo being the parent process of ConHost:
Does this happens if you open CMD, and then run gsudo?
Does this happens if you open CMD /c gsudo?

Test to see If this is caused by gsudo itself (should go away if we change the operation mode):
Does this happens if you open "gsudo --debug --vt" ? (the user experience may be worse, but we are proving a point)
Does this happens if you open "gsudo -i medium --debug" ? (this won't actually elevate)

Could you check if you created any Desktop Shortcut to, for example, "gsudo something" and mapped a key combination?

Can you check this registry key 
    Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Keyboard Layout
    ... and see if there is an "Scancode Map" item there? 

Also, make sure ShareX is also closed, maybe even close everything that you can. Also custom Windows services such as stop screen recording related, or anything that could hook-up keys? just to rule out some app or service

**Comment by itshoro** [comment]
Hey,

It _doesn't_ happen when I use `gsudo` instead of `sudo`.

I also just did notice that I can reproduce this by just starting `sudo` or `gsudo` without any application (sudo makes the "L"-key not work, it's fine with gsudo)

If I open just `gsudo` I can type L normally, once I also start an instance of gsudo with sudo it will target that window, you mentioned this is an alias, but shouldn't an alias target the same exe?

If I just start `gsudo` it opens `C:\ProgramData\chocolatey\lib\gsudo\bin\gsudo.exe`, if I start `sudo` it opens `C:\ProgramData\chocolatey\lib\gsudo\bin\sudo.exe`.  But then again, my knowledge about this is to little, to make an assumption here, and maybe that's just how aliases on windows work.

Does this happens if you open CMD, and then run gsudo / sudo? **No**, if I start gsudo in CMD then this doesn't happen.
Does this happens if you open CMD /c gsudo? **No** (also applies to `CMD /c sudo`)

Does this happens if you open "gsudo --debug --vt" ? **No**
Does this happens if you open "sudo --debug --vt" ? **Yes**

Does this happens if you open "gsudo -i medium --debug" ? **No**
Does this happens if you open "sudo -i medium --debug" ? **Yes**

I don't have any Desktop Shortcut or anything of the likes.

I didn't find a `Scancode Map` item in the registry (only a default item).

I stopped all applications, but gsudo / sudo. The result:
Using `sudo`, the L-Key targets the application,
Using `gsudo`, the L-Key works as intended.

**Comment by gerardog** [comment]
I was able to reproduce it! This is caused by Windows Powertoys "Keyboard Manager".

![image](https://user-images.githubusercontent.com/3901474/93091633-bade6e00-f674-11ea-85cc-6fbfe37e47aa.png)

I had to remove the binding, disable the keyboard manager and restart all gsudo instances to make the problem go away. 
Removing the bindings is not enough. My "L" key no longer works! LOL

**Comment by itshoro** [comment]
Sadly Keyboard Manager is both disabled, and PowerToys (like all other applications, that normally run on my system) wasn't running during all the tests listed above. :(

**Comment by itshoro** [comment]
Hey, just wanted to let you know I just tried to reproduce the issue using Windows 10's Sandbox feature.

I started the sandbox went straight to the chocolatey website and installed it using an elevated powershell.
I then closed powershell and opened a new elevated powershell to run `choco install gsudo -y`.

If I now use Run to invoke `gsudo` here the lower case "L" does work, while invoking `sudo` breaks it. So it seems like it really does have something to do with the alias.

Here a video showing it in the Window Sandbox (I typed `L`, `Shift + L`, `Alt + L`  both times and in the end also showed that pressing L targets the `sudo.exe` window). https://www.youtube.com/watch?v=sYJ6sTvUo3w

**Comment by itshoro** [comment]
Hey I could pin point this problem to the symlink.

You probably knew this, but a Shortcut and a symlink are different from one another as WSL shows us (comparing it to a manually added shortcut, which when invoked doesn't yield the "L" problem).
![image](https://user-images.githubusercontent.com/15874697/93100938-ffd0c780-f6a9-11ea-8bb2-596e5a534f99.png)

Shortcuts don't seem to show up as part of the path. So the only other idea I had was to create a .bat file

```batch
start gsudo.exe %*
```

And starting this through run, does in-fact work, and the "L" key works as intended.

**Comment by gerardog** [comment]
The symlink may be part of the problem, I agree. But as I said Ive been using gsudo a lot and this is not a problem to othes. This only happens if you install some redirection keys maybe only the Powertoys which has a an option to redirect keys for specific processes. The process filter probably fails because of the symlink. Even uninstalling powertoys fix the window focus problem but does not fix the issue where the lowercase L still doesn't work. so there is a registry key left behind Powertoys even after uninstall.
The proper fix, I think, would be to find the reg key to fix your system and mine, and report to powershell tools.
The batch file probably breaks powershell commands. Using a "shim" would normally do the trick, but that one has Ctrl-C issues.
I was going to recommend you to just duplicate gsudo.exe to sudo.exe. The only side effect would be that "gsudo cache" and "sudo cache" would work "kinda" independently. The hard link would work too, haven´t tested. Please keep in mind these manipulations if you "choco upgrade gsudo" in the future, you may have to reapply or correct the result.

Speaking of workarounds: I normally don't sudo/gsudo from explorer, because just typing cmd/pwsh and pressing Ctrl+Shift+Enter is faster.

**Comment by gerardog** [comment]
> It seems there is something fundamentally weird with soft symlinks. And maybe only my devices are affected, I just tried creating a soft symlink for powershell to test my assumption using cmd /c mklink "ps_soft.exe" "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" and yes when running powershell through the symlink (starting it through run) stopped the L-Key from working.

That's it. We have a repro of the problem and it's not a rooted in gsudo. It's affected because the sudo alias is a symlink. I'm pretty sure it's because of PowerToys because it started occurring after I ran `choco upgrade powertoys` (from 0.16 to 0.21) and created my first mapping.
I was also able to 'MKLINK CMD2.EXE C:\Windows\System32\cmd.exe' and reproduce the problem with CMD.

**Comment by itshoro** [comment]
Can confirm just tried it it on a third device which never had PowerToys installed.

Seems like Windows Sandbox copies  or accesses the system registry then, as I could reproduce it there.

I'm sorry this is the first time something like this has happened to me, how should we forward this issue?

**Comment by gerardog** [comment]
> Can confirm just tried it it on a third device which never had PowerToys installed.

I got confused. You confirmed this is not a problem when the user has not installed powertoys, right?

> Seems like Windows Sandbox copies or accesses the system registry then, as I could reproduce it there.

The problem may be at the host of the windows sandbox/virtual machine and when mapping the keyboard thru the virtualization that lets the problem stay. But not sure.

> I'm sorry this is the first time something like this has happened to me, how should we forward this issue?

We should report this to [microsoft/PowerToys](https://github.com/microsoft/powertoys) but with the CMD / powershell example, to rule gsudo out of the equation. We can still mention gerardog/gsudo#58 for reference.

I got a busy day today but maybe tomorrow I can create that issue. Or you can take the lead and I will be listening and contributing to that conversation.

**Comment by itshoro** [comment]
> I got confused. You confirmed this is not a problem when the user has not installed powertoys, right?

Exactly, sorry If I made it sound confusing. 

> I got a busy day today but maybe tomorrow I can create that issue. Or you can take the lead and I will be listening and contributing to that conversation.

Sure thing I'll create an issue there and reference this one. Thanks for the help, and have a great day! 😄
