### ISSUE TITLE
Handle started application exitcode

### ISSUE THREAD

**Issue by lazna** [gerardog/gsudo#61]
Often utilizing `gsudo app parameters` through the batch script. Need to distinguish STDERR and exitcode of `app` from STDERR and exitcode of `gsudo` but did not find any way to do this. Is it possible at all?

**Comment by gerardog** [comment]
Hi,
You can't separate STDERR from gsudo and the elevated app. But you can turn off all gsudo output by setting `LogLevel` to `None`. 
Per command: `gsudo --loglevel none app parameters`
For all elevations: `gsudo config LogLevel None`

You can also set it to `Warning` to hide Info messages or `Error` to hide all but errors.

Regarding the exit code, gsudo either returns 999 (if gsudo failed to elevate), or else it returns the exit code thrown by the elevated app.
Also, if gsudo returns 999, you can asume all STDERR is from gsudo.

Are you using CMD/batch scripts?
Try `if %errorlevel%==999 echo gsudo failed!`

PowerShell?
``` powershell
gsudo Remove-Item ProtectedFile.txt

# Test gsudo success (optional):
if ($LastExitCode -eq 999 ) {
    'gsudo failed to elevate!'
} elseif ($LastExitCode) {
    'Command run elevated but still failed! (Is file in use?)'
} else { 'Success!' }
```

Let me know if this answers your question. 
Regards.-

**Comment by lazna** [comment]
Thanks, it look like it does work.

**Comment by gerardog** [comment]
You are welcome. Let me

**Comment by lazna** [comment]
Did you think to include such information into the program documentation?

**Comment by gerardog** [comment]
In the next release the message `Info: Process exited with code 1` will be changed to Debug level instead of Info, so it won't show up (unless you `--debug`). I think this clears the STDERR scenario for most people.

I will add a mention to the exit code 999 in the command line help. It is mentioned in a few places in the [readme](https://github.com/gerardog/gsudo) but I will see if I can make it more explicit. 

Thanks for the suggestion.
