### ISSUE TITLE
Issue: Unelevated process with fully enabled UAC is still flagged as elevated

### ISSUE THREAD

**Issue by e1sem** [gerardog/gsudo#66]
## Issue Description

@gerardog, I found [this](https://stackoverflow.com/questions/60454914/runas-verb-not-showing-a-uac-popup-and-not-elevating-when-invoked-from-a-proces/60916549#60916549) old question on stackoverflow with mentioning disabled UAC. But I'm experiencing the same problem with fully enabled UAC and enabled administrator credential prompting.
It fails at `GetTokenInformation(..., TOKEN_INFORMATION_CLASS.TokenLinkedToken, ...)` with `ERROR_NO_SUCH_LOGON_SESSION`.
It seems there is no problem with default **Prompt for consent**. The issue appears only if I change the elevation behavior.

Any ideas why Windows refuses providing a linked token?

## Steps to Reproduce

1.  Set **User Account Control** Setting to `Always notify`
2. Change **Elevation Behavior for Administrators** from `Prompt for consent` to `Prompt for credentials`
3. Restart the computer and/or use `Gpupdate /Force` 

## Screenshots

![image](https://user-images.githubusercontent.com/23256325/101188953-13fbe380-365f-11eb-92fa-7ec7f275f74f.png)
![image](https://user-images.githubusercontent.com/23256325/101188932-0c3c3f00-365f-11eb-834d-c22eb8efd421.png)
![image](https://user-images.githubusercontent.com/23256325/101188967-19592e00-365f-11eb-83cc-b740b8aa95e0.png)
![image](https://user-images.githubusercontent.com/23256325/101188977-1c541e80-365f-11eb-89e4-0b3ffd65863f.png)

## Context:
 - Windows version: `Windows 10 Enterprise LTSC v1809`
 - gsudo version: `v0.7.2`

**Comment by gerardog** [comment]
Hi @e1sem,

I've tried your config, and `gsudo` seems to work fine:

![image](https://user-images.githubusercontent.com/3901474/101227623-47e30300-3677-11eb-86dd-4a1d86244b8f.png)

It restricted the process successfully, not admin anymore, right?
Are you reporting a problem with gsudo or a question about UAC?

> Any ideas why Windows refuses providing a linked token?

I'm learning as I go on this matter. I hadn't tried that group policy combination before. Now I did and learned that Windows only provides a split-token (a user token with a linked admin token) if you have the "prompt for consent" mechanism enabled. When you set the group policy to ask for credentials (instead of consent), it seems like the UAC is creating a new admin token from scratch with the user/pass specified. The tokens are not linked, so GetTokenInformation(TokenLinkedToken) fails.

In this scenario, as `gsudo` fails to get the unelevated token, it trims the current admin token using SaferApi. This works, with a minor drawback, processes created with a SaferApi token can not invoke the UAC/consent again to elevate. (so I decided to put SaferApi as fallback method only as it's better than nothing). 

I wish I had the time to read `Windows Internals Part 2` from Mark Russinovich to go deep into this, but I've been quite busy lately. 

Does this helps? Feel free to ask.
