### ISSUE TITLE
Issue: 'sudo' alias is not working after installing 3rd party Chocolatey 'sudo' package.

### ISSUE THREAD

**Issue by jstrese** [gerardog/gsudo#76]
## Issue Description

I just installed gsudo for the first time today after trying out the sudo package. The 'sudo' alias for gsudo doesn't appear to work. I've tried the alias with the command prompt as well as PowerShell.

Version: 0.7.3
OS: Windows 10 Pro (20H2) x64

## Steps to Reproduce

1.  [PowerShell] Install sudo package
2.  [PowerShell] Uninstall sudo package (v0.7.3)
2.  [PowerShell] Install gsudo
3.  [PowerShell] Run sudo notepad

## Screenshots
![image](https://user-images.githubusercontent.com/431341/105609530-8e97d400-5d6f-11eb-9d29-aae6fda4f64b.png)

## Context:
 - Windows version: (Start -> winver)
![image](https://user-images.githubusercontent.com/431341/105609580-dc144100-5d6f-11eb-9817-92fbf0c22f8f.png)

 - gsudo version:      (gsudo -v)
 Included in the first screenshot

**Comment by gerardog** [comment]
Thanks for your detailed report.

This is a duplicate of #48. As you already noticed, this is not caused by `gsudo`. It is an issue in Jan Hebnes' `sudo` chocolatey-package uninstaller, which does not delete it's own `sudo.exe` file. I've submitted a fix for that, see janhebnes/chocolatey-packages#6.

To fix your system, open CMD as Admin and run `DEL "C:\ProgramData\chocolatey\bin\Sudo.exe"`

**Comment by jstrese** [comment]
@gerardog Sorry about that, I'll go ahead and close the issue 👍
