### ISSUE TITLE
Feature request: Use file for config instead of registry?

### ISSUE THREAD

**Issue by highend** [gerardog/gsudo#90]
Hi,

would it be possible to use a config file to get/set settings instead of using registry entries?

Preferable in the same folder where gsudo resides (to make it portable), as long as it's not a uac protected folder (in this case, use %APPDATA%\gsudo\<config file>)

Maybe a gsudo.json or gsudo.ini one and as long as it exists the registry is ignored completely...

Thanks for considering this!

**Comment by gerardog** [comment]
Hi, 
Let me ask you... What benefit would you get? What is your intention by using a config file? or why using the registry does not satisfy your use case?

Using the registry allows the use of global settings, which require admin privileges to write. (CacheMode, CacheDuration)

For example, let's say a user chooses to opt-out of the credentials cache. `sudo config cachemode disabled` would do the trick.
He can now lend his computer to colleagues without worrying they may elevate without his consent. But not if they are able to change their admin settings, by modifying the cache mode, they would enable the cache...

**Comment by highend** [comment]
Hi,

it's already mentioned: It makes gsudo 100% portable. E.g. just copying gsudo's folder to a different pc allows you to use it with the exact environment that it has on the source system. That includes the easiest way of sharing/syncing/updating its config settings...

**Comment by JohnLGalt** [comment]
Can you make something portable that needs to obtain elevated privileges on every system it is used on without first integrating it with said system(s)?

If yes, then that is a massive bug, because systems should not randomly allow elevated processes without integration.

if no, then portability is useless.

**Comment by highend** [comment]
It's not a bug if you want to start something with elevated permissions (as long as you have them)^^

**Comment by JohnLGalt** [comment]
Sorry, no, if you have them then you've already got Registry access.  Which then makes it moot.

**Comment by highend** [comment]
What does that have to do with this feature request? Portability is not about permissions...

**Comment by JohnLGalt** [comment]
> 
> 
> Hi,
> Let me ask you... What benefit would you get? What is your intention by using a config file? or why using the registry does not satisfy your use case?
> 
> Using the registry allows the use of global settings, which require admin privileges to write. (CacheMode, CacheDuration)
> 
> For example, let's say a user chooses to opt-out of the credentials cache. `sudo config cachemode disabled` would do the trick.
> He can now lend his computer to colleagues without worrying they may elevate without his consent. But not if they are able to change their admin settings, by modifying the cache mode, they would enable the cache...

Ummm, perhaps a re-read of that would help.

**Comment by highend** [comment]
Ummm, an option to invalidate / delete the credential cache would solve that "issue"...

**Comment by gerardog** [comment]
> Ummm, an option to invalidate / delete the credential cache

`gsudo -k` does this.

> `gsudo config cachemode disabled`
> do this by default

The cache is already invalidated when you change the cache mode. 

But you are missing the point. Some settings should require admin privileges to be set, otherwise you are breaking the design assumptions and those settings are useless from a security standpoint. Even more, users who disabled the cache would have a fake sense that it is disabled for the whole system but only local write access (not-admin) is required to enable it again.

I recommend you export gsudo settings:

Current User: `reg export HKCU\SOFTWARE\gsudo gsudo-UserSettings.reg` 
Shared settings (system): `reg export HKLM\SOFTWARE\gsudo gsudo-SystemSettings.reg` 
...then import both .reg files on each machine you want to use.

or just write a batch file with your desired configuration and run it on each station.
``` 
gsudo config cachemode auto
gsudo config Prompt "$p [Admin]$g"
```

BTW, you haven't told me which settings do you change often. If the issue is that you want to use the cache but don't want to leave a regkey forever, then you can still use `gsudo cache on` which will show one UAC and allow elevations for the current console or 'gsudo cache on -pid 0' to allow any process to elevate.
