### ISSUE TITLE
Issue: gsudo launches a 64 bit cmd when ran in a 32-bit cmd (on x64)

### ISSUE THREAD

**Issue by alexaka1** [gerardog/gsudo#92]
## Issue Description

When opening a new command promtp via `gsudo -n` from the 32-bit cmd, the new window will be 64-bit.
If you run `gsudo echo %ProgramFiles%` in a 32-bit cmd, then it correctly displays `C:\Program Files (x86)`.
However when `gsudo -n echo %ProgramFiles%` is run, the new window pops up for a moment and correctly displays `C:\Program Files (x86)`, then it closes.
But when running just `gsudo -n` and then in the new window `echo %ProgramFiles%`, it will display `C:\Program Files`.

## Steps to Reproduce

1.  Open `C:\Windows\SysWOW64\cmd.exe`
2.  Type `gsudo -n`
3.  Type `echo %ProgramFiles%` in the new window that popped up

## Context:
 - Windows version: 20H2 (19042.928)
 - gsudo version:    v0.7.3

**Comment by alexaka1** [comment]
This is just my sidenote: it would be cool to provide gsudo an option to launch a new cmd with the specified version (32/64-bit).

**Comment by gerardog** [comment]
Hi Alex, thanks for reporting the issue. I was able to reproduce it.
gsudo <= 0.7.3 always launches the 64-bit flavor of cmd.

But please note that if you do `gsudo echo %ProgramFiles%` the variable expansion is done *before* calling gsudo, therefore this method fails to detect whether gsudo correctly creates a 32 or 64 bit process. Keeping this in mind, you will see that the `-n` argument has no relationship with this bug. (But it works if you escape the % sign like this: `gsudo echo ^%programfiles^%`, or use Task Manager to detect if it is 32 or 64: go to the Details tab, and add the Platform column.) 

I´ve pushed a fix, and now gsudo will use the invoker CMD,EXE, that would keep the same bitness.

>  it would be cool to provide gsudo an option to launch a new cmd with the specified version (32/64-bit).

The thing is that apps are compiled for a specific environment. You can not choose it's bitness. You can choose a different app, like `%windir%\SysWoW64\cmd.exe` (32 bits) instead of `%windir%\system32\cmd.exe` (64 bits). 

What makes it more confusing is that for 32-bits processes the `system32` folder is actually redirected to 'SysWoW64'. This is problem for us given that a 32-bit process that hypotetically calls 'system32\cmd.exe' is actually calling 'SysWoW64\cmd.exe', but if that 32 bit process calls `gsudo system32\cmd.exe`, then gsudo which will be a 64 bit process will not be redirected by windows therefore will launch the real `system32\cmd.exe`, a 64 bit process.

In other words, file paths are interpreted differently by 32-bit and 64-bit processes, and gsudo is a 64-bit process (on x64 platforms) so there will always be this 'risk' of misinterpreting the input.

So after this fix:

* `gsudo` or `gsudo {command}` will keep the same bitness. 
   (As long as {command} does not include a reference to a cmd.exe for example:)

* `gsudo c:\windows\SysWoW64\cmd.exe` will always launch a 32 bit cmd.
* `gsudo c:\windows\system32\cmd.exe` or `gsudo cmd` will launch a 64 bit cmd.

or

* `gsudo notepad' will always launch the 64 bits version of notepad.
* `gsudo c:\Windows\SysWOW64\notepad.exe` will launch the 32 bit version.

Please, download [this build](https://ci.appveyor.com/project/gerardog/gsudo/builds/40185444/artifacts) and test the fix. Let me know if it solves the issue for you.
